name: Feature Request
description: Propose an enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: What should be built?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      placeholder: What user problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      placeholder: Describe your preferred implementation.
    validations:
      required: true
